repository:
  # The name of the repository. Changing this will rename the repository
  name: pipeline-api

  # A short description of the repository that will show up on GitHub
  description: Pipeline One Backend API

  # A URL with more information about the repository
  homepage: https://github.com/Sawoo-io/pipeline-api

  # Either `true` to make the repository private, or `false` to make it public.
  private: true

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: false

  # Updates the default branch for this repository.
  default_branch: dev

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: back-end
    description: Back-end development
    color: 412b9b
  - name: bug
    description: Something isn't working
    color: CC0000
  - name: feature
    color: 336699
