spring:
  application:
    name: pipeline-one-api
  profiles:
    active: ${activatedProperties}
  messages:
    basename: message
    fallback-to-system-locale: true
    use-code-as-default-message: false
management:
  endpoint:
    health:
      enabled: true
    env:
      enabled: true
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, env, loggers

logging:
  level:
    root: ${rootLogLevel}
    com.sawoo.pipeline: DEBUG


app:
  version: ${version}
  jwt:
    secret: defeAtmarmalaDeheatIngcyAn
  cors:
    allowed-methods: GET,POST,HEAD,PUT,DELETE,OPTIONS

---
spring:
  profiles: dev-local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pipeline-core
      auto-index-creation: false

app:
  server: "http://localhost:8080"
  report-api: "http://localhost:4001"
  mail:
    contact-account: miguel.maquieira@sawoo.io
  cors:
    allowed-origins: http://localhost:4200, http://saas.localhost:4200, http://laas.localhost:4200, http://localhost:8080

---
spring:
  profiles: dev-cloud-db
  data:
    mongodb:
      auto-index-creation: false
      uri: mongodb+srv://pipeline-core-user:verysecretpassword@cluster0.ag5sn.mongodb.net/pipeline-core?retryWrites=true&w=majority

app:
  server: "http://localhost:8080"
  report-api: "http://localhost:4001"
  mail:
    contact-account: miguel.maquieira@sawoo.io
  cors:
    allowed-origins: http://localhost:4200, http://saas.localhost:4200, http://laas.localhost:4200, http://localhost:8080

---
spring:
  profiles: unit-tests
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pipeline-core-test
      auto-index-creation: false

app:
  server: "http://localhost:8080"
  report-api: "http://localhost:4001"
  mail:
    contact-account: miguel.maquieira@sawoo.io

---
spring:
  profiles: unit-tests-embedded
  data:
    mongodb:
      host: localhost
      port: 0
      database: pipeline-core-test
      auto-index-creation: false

app:
  server: "http://localhost:8080"
  report-api: "http://localhost:4001"
  mail:
    contact-account: miguel.maquieira@sawoo.io

---
spring:
  profiles: dev
  data:
    mongodb:
      auto-index-creation: false
      uri: mongodb+srv://pipeline-core-user:verysecretpassword@cluster0.ag5sn.mongodb.net/pipeline-core?retryWrites=true&w=majority

# To fix GAE issue:
# App is listening on port 8080, it should instead listen on the port defined by the PORT environment variable.
# As a consequence, nginx cannot be started. Performance may be degraded. Please listen on the port defined by the
# PORT environment variable
server:
  port: 8081

app:
  server: "https://pipeline-one-dev.ew.r.appspot.com"
  report-api: "http://pipeline-one-report-api-dot-pipeline-api-dev.ew.r.appspot.com"
  mail:
    contact-account: miguel.maquieira@sawoo.io
  cors:
    allowed-origins: https://pipeline-web-dev.ew.r.appspot.com

---
spring:
  profiles: test

# To fix GAE issue:
# App is listening on port 8080, it should instead listen on the port defined by the PORT environment variable.
# As a consequence, nginx cannot be started. Performance may be degraded. Please listen on the port defined by the
# PORT environment variable
server:
  port: 8081

app:
  server: "https://pipeline-api-test.ew.r.appspot.com"
  report-api: "http://pipeline-one-report-api-dot-pipeline-api-test.ew.r.appspot.com"
  mail:
    contact-account: miguel.maquieira@sawoo.io
  cors:
    allowed-origins: https://pipeline-web-test.ew.r.appspot.com



---
spring:
  profiles: prod

# To fix GAE issue:
# App is listening on port 8080, it should instead listen on the port defined by the PORT environment variable.
# As a consequence, nginx cannot be started. Performance may be degraded. Please listen on the port defined by the
# PORT environment variable
server:
  port: 8081

app:
  server: "https://pipeline-api-prod.ew.r.appspot.com"
  report-api: "http://pipeline-one-report-api-dot-pipeline-api-prod.ew.r.appspot.com"
  mail:
    contact-account: miguel.maquieira@sawoo.io
  cors:
    allowed-origins: https://pipeline-web-prod.ew.r.appspot.com



